Introduction Chapter Finished / CLA Assigned
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #224
Opened 2021-06-17 02:35 UTC by KoreaComK

Finished the introduction chapter.
I didn't changed the chapters files names since @nyxnor said that he started to make this changes.

2021-06-17 15:11 UTC, lukedevj commented on 01_0_Introduction.md
> +# CAPÍTULO 1: Introdução à Aprendizagem do Bitcoin Core (& Lightning Network) na linha de comando
<p> Instead of using "na linha de comando" use "pela linha de comando" </p>

2021-06-17 17:23 UTC, lukedevj commented on 01_1_Introducing_Bitcoin.md
> +O Bitcoin é um sistema programável que permite a transferência da moeda bitcoin. Tem como base um sistema descentralizado _peer-to-peer_ (de ponta à ponta) de nodes, que inclui full nodes, carteiras
"pseudonimato" to "pseudo-anonimato".

2021-06-17 17:23 UTC, lukedevj commented on 01_1_Introducing_Bitcoin.md
> +O Bitcoin é um sistema programável que permite a transferência da moeda bitcoin. Tem como base um sistema descentralizado _peer-to-peer_ (de ponta à ponta) de nodes, que inclui full nodes, carteiras
"pseudonimato" to "pseudo-anonimato".

2021-06-17 19:06 UTC, lukedevj requested changes

2021-06-17 19:44 UTC, KoreaComK commented
All changes included in the PR.

2021-06-21 02:08 UTC, lukedevj commented on pt/15_1_Accessing_Bitcoind_with_C.md
> +Para usar o ``libbitcoinrpc``,  precisemos instalar uma configuração básica C e os pacotes dependentes, que são ``libcurl``, ``libjansson``, e ``libuuid``. Depois faremos isso no seu servidor Standup
"precisemos" to "precisaremos"

2021-06-21 02:09 UTC, lukedevj commented on pt/15_1_Accessing_Bitcoind_with_C.md
> +You can then download [libbitcoinrpc from Github](https://github.com/gitmarek/libbitcoinrpc/blob/master/README.md). Clone it or grab a zip file, as you prefer.
Remova esta linha.

2021-06-21 02:11 UTC, lukedevj commented on pt/15_1_Accessing_Bitcoind_with_C.md
> +If that works, you can install the package:
Esqueceu de traduzir esta parte.

2021-06-21 02:15 UTC, lukedevj commented on pt/15_1_Accessing_Bitcoind_with_C.md
> +You use the `rpc_client` variable that you already learned about in the previous test, and add on your `getmininginfo` method and the two other objects:
**Remova esta linha**

2021-06-21 02:18 UTC, lukedevj commented on pt/15_1_Accessing_Bitcoind_with_C.md
> +Assim como quando estávamos usando o [curl](04_4__interlude_using_curl.md), descobrimos que o RPC retorna um objeto JSON contendo um ``ID``, um ``error`` e, mais importante, um objeto JSON do tipo ``
**Assim como ("quando" -> remove) estávamos usando o**

2021-06-21 14:13 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +> :information_source: **NOTE:** This section has been recently added to the course and is an early draft that may still be awaiting review. Caveat reader.
Remove this line.

2021-06-21 15:22 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +rpc_client = bitcoinrpc_cl_init_params ("bitcoinrpc", "YOUR-RPC-PASSWD", "127.0.0.1", 18332);
"bitcoinrpc_cl_init_params (" -> remove this space before the "("

2021-06-21 15:32 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +lu_response = bitcoinrpc_resp_get (btcresponse);
remove this space before the (

2021-06-21 15:42 UTC, KoreaComK commented
Changes made.
Also including the language specification in the code.

2021-06-21 15:43 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +### Etapa 5: Criando uma alteração de endereço
Your mistranslation is not a "alteração", it is "Criando um endereço de troco".

2021-06-21 15:44 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +Repita a metodologia padrão de pesquisa RPC para obter uma alteração de endereço:
Same problem as above comment.

2021-06-21 15:45 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +lu_response = bitcoinrpc_resp_get (btcresponse);
remove the space before the (

2021-06-21 15:58 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +Para criarmos esses parâmetros corretamente, precisaremos revisar o que o RPC ``createrawtransaction`` espera que passemos de informação. Felizmente, isso é fácil de determinar usando a funcionalidad
"espera que passemos de informação" to "espera que passemos como argumento "

2021-06-21 16:23 UTC, lukedevj commented on pt/15_2_Programming_Bitcoind_with_C.md
> +Vamos usar o método normal para criar da chamada ao RPC:
"Vamos usar o método normal para criar" [da to uma] "chamada ao RPC".

2021-06-21 17:36 UTC, lukedevj reviewed
Revised Chapter 15 waiting for change.

2021-06-22 18:18 UTC, shannona commented
Hey Folks,

Great to see this coming along, and it looks like you're following a great process with one author, one editor, and making revisions based on that.

Thank you! I'm very much looking forward to this going forward and us having a great Portuguese translation of Learning Bitcoin in the near future.

Two issues that I see right now:

1.) Something in your process is leading you to delete the original English files. Take a look at the diffs, and you'll see the English version of the files you've been translating have been deleted: https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/224/files

Obviously, we need to get that resolved before we can do any merges. My suggestion is that you rebranch and then copy in your Portuguese translations, but whatever works for you is fine, as long as our original files will still be there when we merge.

2.) I'm not getting a good milestone to merge on because by the time one section is revised, the next is being written. Two possible solutions for this:

A.) Pause and give me a milestone to merge in the days I'm around (see below).

B.) Create a new fork for each chapter. This is actually what we'll be suggesting when I revise the TRANSLATING docs, now that we've seen how things work. This way, you create a fork, you add a chapter, you send a PR, you review it, you revise it, and then you alert me that it's finalized and ready for a merge.

Whichever works for you is fine, just under the current methodology this might not get merged until the end, which is subpar.

==
As a general note, I usually spend Tuesday & Wednesday (Hawaiian time) on Blockchain Commons projects, with my other days spent writing for other people (and working on my own books in process). That means that I'll usually delay any comments, merges, etc., until Tuesday, and that if you want to use the first methodology, where you pause and ask me to merge after everything is revised, that'd usually happen 7.30 am - 3.30 pm HST on Tuesday and Wednesday.

Thanks again! Let me know when the issue with the deleted files is resolved (either here or by creating a new PR from a new branch) and when everything is at a point where it's been reviewed and revised and can be merged (by either of the methods i suggest).

2021-06-24 21:46 UTC, KoreaComK commented
Changes pointed by @lukedevj of Chapter 15 made.

@shannona thanks for the feedback and for showing a plan to translation.
I already finished to made the changes and also I included the deleted files. So, I think now it could be merged.
I will fork and make a PR one chapter per time from now to future, to get the things more organized.

Cheers!

2021-06-24 23:35 UTC, nyxnor commented
@KoreaComK 
> ## Create a new fork for each chapter.
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/224#issuecomment-866224009

A new fork in a new PR. Keep 1 chapeter per PR.

2021-06-24 23:57 UTC, closed without merging