chapter 05_0 translated and ready for review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #227
Opened 2021-06-18 17:42 UTC by icculp

Translated and ready for review by native speaker

2021-06-21 21:12 UTC, javiervargas commented on es/05_0_Controlling_Bitcoin_Transactions.md
> +Enviar una transacción no siempre es el final de la historia. Al usar los protocolos RBF (reemplazo por tarifa) y CPFP (el niño paga por el padre), un desarrollador puede continuar controlando la tra
el verdadero poder de

2021-06-21 21:12 UTC, javiervargas requested changes
Fix typos

2021-06-22 19:27 UTC, shannona commented
Folks,

Great to see this all coming along! It looks like the system of one person writing and another reviewing, leading to revisions is working well, and the way that you're keeping each section to a PR is keeping it all nice and clean.

I am assuming this is still in process. If (and when) it's ready to go, I just need either the reviewer to actually check off that it's ready, or either of you to post a comment saying it's ready for a merge.

Thanks again! Very exciting to see this translation going forward.

2021-06-22 20:46 UTC, javiervargas commented
Still we need to check some internals links,   although translation  it's ok.

2021-06-23 21:38 UTC, shannona commented
Great. Just let me know when it's ready to merge.

2021-06-29 18:45 UTC, shannona commented
Hey folks, just wanted to check in and see how things are going on the Spanish translation. No rush, I just want to make sure that *I'm* not holding things up. When each PR has been reviewed and revised, the best way to alert me is to either request a review from me or to tag me in a comment telling me you're ready to merge, and I'll then do so.

2021-07-20 18:58 UTC, javiervargas approved these changes

2021-07-20 22:42 UTC, merged