chapter 05_2 translated, ready for review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #231
Opened 2021-06-20 00:54 UTC by icculp

2021-06-21 20:34 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +> :book: ***¿Debo confiar en transacciones sin confirmaciones?*** No, nunca. Esto era cierto antes de RBF y fue cierto después de RBF. Las transacciones deben reibir confirmaciones antes de que sean
deben recibir

2021-06-21 20:35 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +Ahora, cuando mire a su transacción, deberías ver algo nuevo: la línea `bip125-replaceable`, que siempre ha sido marcada como `no` antes, ahora está marcada como `yes` (sí):
debería ver algo nuevo

2021-06-21 20:35 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +> :information_source: **NOTA — SECUENCIA:** Este es el primer uso del valor `nSequence` en Bitcoin. Puede configurarlo entre 1 y 0xffffffff-2 (4294967293) y habilitar RBF, pero si no tiene cuidado,
establecerlo

2021-06-21 20:36 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +Si lo prefiere, puede _siepmre_ optar por RBF. Hágalo ejecutando su `bitcoind` con el comando `-walletrbf`. Cuando ya hecho esto (y reiniciado su `bitcoind`), todos los UTXOs deberían tener un número
puede _siempre_ optar por RBF.

2021-06-21 20:38 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +> :book: ***¿Qué es un doble-gasto?*** Un doble-gasto ocurre cuando alguien envía los mismos fondos electrónicos a dos personas diferentes (o, a la misma persona dos veces, en dos transacciones difer
Se resuelve en Bitcoin

2021-06-21 20:42 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +Nuestros destinatarios tienen su dinero, y la transacción fallida original eventualmente se sald´ra del mempool.
se saldra

2021-06-21 20:45 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +> :warning: **ADVERTENCIA DE VERSIÓN:** El `bumpfee` que RPC requiere Bitcoin Core v.0.14.0.
El `bumpfee` por RPC requiere

2021-06-21 20:45 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +Si una transacción está atascada y no desea esperar a que caduque por completo, si optó por RBF, puede gastar el doble con RBF para crear una transacción de reemplazo (o simplemente usar `bumpfee`).
puede gastarla dos veces con RBF

2021-06-21 20:47 UTC, javiervargas commented on es/05_2_Resending_a_Transaction_with_RBF.md
> +> Por ejemplo, puede enviar una transacción y luego, antes de que se confirme, combinarla con una segunda transacción. Esto le permite comrpimir múltiples transacciones en una sola, disminuyendo las
le permite comprimir

2021-06-21 20:47 UTC, javiervargas requested changes
Fix typos

2021-06-22 20:36 UTC, javiervargas approved these changes
Ok

2021-07-20 18:47 UTC, shannona commented
Merging approved PR. Thanks!

2021-07-20 18:47 UTC, merged