chapter 09_1 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #247
Opened 2021-06-27 18:25 UTC by icculp

2021-06-29 07:54 UTC, javiervargas requested changes

2021-06-29 07:54 UTC, javiervargas commented on es/09_1_Understanding_the_Foundation_of_Transactions.md
> +En realidad, no es necesario que lo envíes: el objetivo es simplemente producir una transacción completa que pueda examinar.
En realidad, no es necesario que lo envíe:

2021-06-29 07:54 UTC, javiervargas commented on es/09_1_Understanding_the_Foundation_of_Transactions.md
> +El `scriptSig` se encuentra en el `vin`. Este es el script de _desbloqueo_. Es lo que se ejecuta para acceder al UTXO que se utiliza para financiar esta transacción. Habrá uno `scriptSig` por UTXO en
Habrá un `scriptSig` por UTXO en una transacción

2021-06-29 21:31 UTC, icculp commented on es/09_1_Understanding_the_Foundation_of_Transactions.md
> +Como se describe en el [Chapter 1](01_0_Introducing_Bitcoin.md), los fondos en cada transacción de Bitcoin están bloqueados con un rompecabezas criptográfico. Para ser precisos, dijimos que Bitcoin s
I'm blind, I don't see the typo to correct for this line. Please clarify

2021-06-30 07:35 UTC, javiervargas approved these changes

2021-06-30 07:36 UTC, javiervargas commented on es/09_1_Understanding_the_Foundation_of_Transactions.md
> +Como se describe en el [Chapter 1](01_0_Introducing_Bitcoin.md), los fondos en cada transacción de Bitcoin están bloqueados con un rompecabezas criptográfico. Para ser precisos, dijimos que Bitcoin s
At the end:
Esos **sripts**, que bloquean y desbloquean transacciones, están escritos en Bitcoin Script.
Esos **scripts**, que bloquean y desbloquean transacciones, están escritos en Bitcoin Script.

2021-06-30 13:15 UTC, icculp commented on es/09_1_Understanding_the_Foundation_of_Transactions.md
> +Como se describe en el [Chapter 1](01_0_Introducing_Bitcoin.md), los fondos en cada transacción de Bitcoin están bloqueados con un rompecabezas criptográfico. Para ser precisos, dijimos que Bitcoin s
I see it now, geez was I blind. Thanks

2021-07-20 18:48 UTC, merged