Spanish translation
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #266
Opened 2021-07-08 18:42 UTC by srahalh

2021-07-09 21:35 UTC, javiervargas requested changes
Pending update table of contents

2021-07-09 21:35 UTC, javiervargas commented on 04_0_Sending_Bitcoin_Transactions.md
> +Este capítulo describe tres metodos diferentes para enviar bitcoins a direcciones tipicas P2PKH desde lineas de comandos, usando unicamente la interfaz de bitcoin-cli.
Este capítulo describe tres metodos diferentes para enviar bitcoins a direcciones tipicas P2PKH desde la línea de comandos, usando unicamente la interfaz de bitcoin-cli.

2021-07-29 09:48 UTC, javiervargas approved these changes

2021-07-30 16:22 UTC, javiervargas requested changes

2021-07-30 16:22 UTC, javiervargas commented on 04_1_Sending_Coins_The_Easy_Way.md
> +Mientras espera a que esta transacción se complete, notará que `bitcoin-cli getbalance` muestra que todo su dinero ha desaparecido (o, al menos, todo su dinero de una única transacción entrante). Del
Mientras espera a que esta transacción se complete, notará que `bitcoin-cli getbalance` muestra que todo su dinero ha desaparecido (o, al menos, todo su dinero de una única transacción entrante). Del mismo modo, `bitcoin-cli listunspent` mostrará que toda la transacción ha desaparecido, incluso si era más de lo que quería enviar. Hay una razón para esto: cada vez que ingresa dinero, tendra que enviarlo _todo_ junto, y si quiere conservar algo, tendra que hacer algunos malabares. Una vez más, `sendtoaddress` se encarga de todo esto por usted, lo que significa que no tiene que preocuparse de hacer el cambio hasta que envíe una transacción en crudo. En este caso, aparecerá una nueva transacción con el cambio cuando el gasto se incorpore a un bloque.

2021-07-30 16:22 UTC, javiervargas commented on 04_1_Sending_Coins_The_Easy_Way.md
> +Para enviar monedas de forma fácil, asegúrate de que los valores predeterminados de la transacción son racionales, consigue una dirección y envía monedas allí. ¡Por eso lo llaman fácil!
Para enviar monedas de forma fácil, asegúrese de que los valores predeterminados de la transacción son racionales, consigue una dirección y envía monedas allí. ¡Por eso lo llaman fácil!

2021-07-30 16:22 UTC, javiervargas commented on 04_1_Sending_Coins_The_Easy_Way.md
> +> _Las ventajas._ Es facil. No tiene que preocuparte de cosas arcaicas como los UTXOs. No tiene que calcular las comisiones a mano, por lo que no es probable que cometa errores que le cuesten grandes
No tiene que preocuparse de cosas arcaicas como los

2021-07-30 16:22 UTC, javiervargas commented on 04_1_Sending_Coins_The_Easy_Way.md
> +Continua "Enviando transacciones en Bitcoin" con [§4.2 Creando una Transacción en Crudo](04_2_Creating_a_Raw_Transaction.md).
Continúe

2021-08-08 20:40 UTC, javiervargas requested changes
Pending review and update final links

2021-09-14 18:43 UTC, shannona commented
Replaced by later work.

2021-09-14 18:43 UTC, closed without merging