Chapter 10.4 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #270
Opened 2021-07-10 05:14 UTC by icculp

2021-07-13 16:16 UTC, javiervargas requested changes

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +Luego, se saque un elemento más por error:
Luego, se saca un elemento más por error:

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +En general, se trataba de problemas con cualquier tipo de script de Bitcoin complejo, pero rápidamente se convirtieron en problemas muy reales cuando se aplicaron a multifirmas, que fueron algunos de
Estos eran generalmente problemas con cualquier tipo de script de Bitcoin complejo,

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +> :book: ***¿Qué es un P2SH multifirma?*** Las multifirmas P2SH fueron la primera implementación de transacciones P2SH. Simplemente empaquetan una transacción estándar de múltiples firmas en una tran
> :book: ***¿Qué es un P2SH multifirma?*** Las multifirmas P2SH fueron la primera implementación de transacciones P2SH. Simplemente empaquetan una transacción estándar de múltiples firmas en una transacción P2SH estándar.  Esto permite la estandarización de direcciones; reduce el almacenamiento de datos; y aumenta los recuentos de "m" y "n".

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +### Cree la Cerradura para P2SH Multifirma
Crear el bloqueo para una P2SH Multifirma

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +## Desbloquear el P2SH Multifirma
Desbloquear la Multifirma P2SH

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +4. Tener éxito si el `<serializedMultisig>` coincide con el `<hashedMultisig>`.
4. Es correcto si el `<serializedMultisig>` coincide con el `<hashedMultisig>`.

2021-07-13 16:16 UTC, javiervargas commented on es/10_4_Scripting_a_Multisig.md
> +4. Tener éxito si los operandos cumplen con la deserialización `redeemScript`.
4. Es correcto si los operandos cumplen con la deserialización `redeemScript`.

2021-07-17 15:22 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +Antes de crerrar esta introducción a las secuencias de comandos P2SH, vale la pena examinar un ejemplo más realista. Desde [§6.1](06_1_Sending_a_Transaction_to_a_Multisig.md), hemos estado diciendo c
Ohh this was outdated, since I fixed it in 
c9127e4. Maybe the version you saw was from commit 
b3d0625, but I did that before the PR

2021-07-17 15:26 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +Como se explica en [§10.1: Creación de un Bitcoin Script con P2SH](10_1_Building_a_Bitcoin_Script_with_P2SH.md), las multifirmas con uno de los tipos de transacciones estándar de Bitcoin. Se puede cr
Resolved in previous commit

2021-07-17 15:29 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +Entonces, el `OP_CHECKMULTISIG` comienz a ejecutarse. Primero se saca el "2":
Previous commit

2021-07-17 15:30 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +Luego, el "2" le dice a `OP_CHECKMULTISIG` to saque dos firmas:
Prev commit

2021-07-17 15:32 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +> :book: ***¿Qué es un P2SH multifirma?*** Las multifirmas P2SH fueron la primera implementación de transacciones P2SH. Simplemente empaquetan una transacción estándar de múltiples firmas en una tran
Previous commit

2021-07-17 15:32 UTC, icculp commented on es/10_4_Scripting_a_Multisig.md
> +### Cree la Cerradura para P2SH Multifirma
Prev commit

2021-07-20 22:44 UTC, merged