Chapter 10.5 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #283
Opened 2021-07-17 19:20 UTC by icculp

2021-07-18 17:41 UTC, javiervargas requested changes

2021-07-18 17:41 UTC, javiervargas commented on es/10_5_Scripting_a_Segwit_Script.md
> +La dirección P2SH-Segwit es una raza en extinción. Básicamente, fue una medidia provisional mientras Bitcoin estaba en transición a Segwit que permitía a un usuario crear una dirección de Segwit y lu
Básicamente, fue una medida provisional mientras Bitcoin

2021-07-18 17:41 UTC, javiervargas commented on es/10_5_Scripting_a_Segwit_Script.md
> +The address starts with a `2` (or a `3`) revealing it as a script
This is in English....

2021-07-18 17:42 UTC, javiervargas approved these changes

2021-07-18 17:49 UTC, javiervargas requested changes

2021-07-18 17:49 UTC, javiervargas commented on es/10_5_Scripting_a_Segwit_Script.md
> +## Resumen: Programación de un Hash de Clave Pública de Pagar Para Precenciar
## Resumen: Programando un pago al testigo de una clave publicada codificado.

2021-07-18 18:10 UTC, icculp commented on es/10_5_Scripting_a_Segwit_Script.md
> +The address starts with a `2` (or a `3`) revealing it as a script
Old commit

2021-07-20 19:03 UTC, javiervargas approved these changes

2021-07-20 22:44 UTC, merged