Chapter 19.4 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #309
Opened 2021-07-25 18:12 UTC by icculp

2021-07-25 20:08 UTC, javiervargas requested changes

2021-07-25 20:08 UTC, javiervargas commented on es/19_4_Lightning_Network_Review.md
> +Un complementos puede estar escrito en cualquier idioma y puede comunicarse con `lightningd` a través de stdin y stdout del complemento. JSON-RPCv2 se utiliza como protocolo en la parte superior de l
Un complementos puede estar escrito en cualquier lenguaje y puede comunicarse con

2021-07-25 20:08 UTC, javiervargas commented on es/19_4_Lightning_Network_Review.md
> +Su nodo Lightning debe estar en línea todo el tiempo; de lo contrario, su contraparte podría enviar en estado de canal anterior y robar sus fondos. Sin embargo, existe otro escenario en el que se pue
su contraparte podría enviar un estado de canal anterior y robar sus fondos.

2021-07-25 20:08 UTC, javiervargas commented on es/19_4_Lightning_Network_Review.md
> +Ahora sal y haz de la comunidad Blockchain un lugar mejor!
Ahora salga y haga de la comunidad Blockchain un lugar mejor!

2021-07-30 16:09 UTC, javiervargas requested changes

2021-07-30 16:09 UTC, javiervargas commented on es/19_4_Lightning_Network_Review.md
> +Un complementos puede estar escrito en cualquier lenguaje y puede comunicarse con `lightningd` a través de stdin y stdout del complemento. JSON-RPCv2 se utiliza como protocolo en la parte superior de
Un complemento puede estar escrito en cualquier

2021-08-08 20:42 UTC, javiervargas approved these changes

2021-08-08 20:42 UTC, javiervargas commented
@shannona ready to be merged

2021-08-10 18:08 UTC, shannona commented
Great.

2021-08-10 18:08 UTC, merged