01_0_Introduccion.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #316
Opened 2021-07-29 10:45 UTC by javiervargas

01_0_Introduccion.md

2021-07-29 21:42 UTC, icculp requested changes

2021-07-30 17:53 UTC, icculp approved these changes

2021-08-03 02:55 UTC, icculp commented
@shannona ready to be merged

2021-08-03 19:17 UTC, shannona commented
Thank you

2021-08-03 19:17 UTC, merged