Chapter 02 -2 02_2_Configurando_Bitcoin_Core_Otros.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #320
Opened 2021-07-29 10:58 UTC by javiervargas

2021-07-31 16:05 UTC, csralvall requested changes

2021-07-31 16:05 UTC, csralvall commented on es/02_2_Configurando_Bitcoin_Core_Otros.md
> +* [Configuración de un nodo Bitcoin en una Raspberry Pi 3](https://medium.com/@meeDamian/bitcoin-full-node-on-rbp3-revised-88bb7c8ef1d1). * Damian Mee explica
Add `* *` to beginning of link and remove space  after it to display italics.

2021-07-31 16:05 UTC, csralvall commented on es/02_2_Configurando_Bitcoin_Core_Otros.md
> +* Continúe con "bitcoin-cli" con el [Capítulo tres: Entendiendo la configuración de Bitcoin](03_0_Entendiendo_su_configuracion_Bitcoin.md).
From list of chapters in LEEME.md: `[3.0: Entendiendo Su Configuración Bitcoin](03_0_Entendiendo_Su_Configuracion_Bitcoin.md)`

2021-07-31 16:46 UTC, javiervargas commented on es/02_2_Configurando_Bitcoin_Core_Otros.md
> +# 2.2: Configuración de una máquina Bitcoin-Core a través de otros medios
Las mayúsculas no van.

2021-08-01 14:46 UTC, javiervargas commented on es/02_2_Configurando_Bitcoin_Core_Otros.md
> +* [Uso de otros scripts de Bitcoin Standup](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts). * Blockchain Commons también ofrece una versión del
I dont see it.

2021-08-01 16:26 UTC, csralvall approved these changes
@shannona

2021-08-03 19:38 UTC, merged