Chapter 16-01 16_1_Accediendo_a_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #350
Opened 2021-07-29 17:19 UTC by javiervargas

2021-08-05 01:23 UTC, icculp requested changes

2021-08-05 01:23 UTC, icculp commented on es/16_1_Accediendo_a_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +(Si prefiere mancillar su `/usr/lib`, la alternativa es cambiar su `etc/ld.so.conf` o sus archivos dependientes de manera apropiada  ... pero para una configuración de prueba en una máquina de prueba
Si prefiere no mancillar

2021-08-05 01:23 UTC, icculp commented on es/16_1_Accediendo_a_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +El código de prueba se puede encontrar en el directorio src [15_1_testbitcoin.c ](src/15_1_testbitcoin.c). Descárguelo en su máquina de testnet, luego inserte la contraseña de RPC correcta (y cambie
[15_1_testbitcoin.c] (remove space)
../src/15_1_testbitcoin.c

2021-08-05 01:23 UTC, icculp commented on es/16_1_Accediendo_a_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Recupere el código de prueba del [directorio src](15_1_getmininginfo.c).
../src/15_1_getmininginfo.c

2021-08-05 17:45 UTC, icculp requested changes

2021-08-05 17:45 UTC, icculp commented on es/16_1_Accediendo_a_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Recupere el código de prueba del [directorio src](../15_1_getmininginfo.c).
../src/15_1_getmininginfo.c

2021-08-10 19:43 UTC, icculp approved these changes

2021-08-10 19:43 UTC, icculp commented
@shannona ready to be merged

2021-08-10 20:02 UTC, shannona commented
Merging.

2021-08-10 20:02 UTC, merged