Chapter 16-2 16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #351
Opened 2021-07-29 17:29 UTC by javiervargas

2021-08-05 01:45 UTC, icculp requested changes

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Sin embargo, el verdadero trabajo consiste en decodificar la respuesta. La sección anterior señalaba que la biblioteca `jansson` era "algo torpe" y por eso: tiene que crear (y borrar) un conjunto muy
objetos \`json_t\` para

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Para crear correctamente estos parámetros, deberá revisar lo que espera el RPC `createrawtransaction`. Afortunadamente, esto es fácil de determinar usando la funcionalidad bitcoin-cli help`:
funcionalidad \`bitcoin-cli help\`:

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Para crear el objeto de entrada para su UTXO, use `json_object`, luego rellénelo con valores-clave usando` json_object_set_new` (para referencias recién creadas) o `json_object_set` (para referencias
usando \`json_object_set_new\`

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Notará que nuevamente tiene que traducir cada tipo de variable C en un tipo de variable JSON usando la función apropiada, como `json_string` o` json_integer`.
como \`json_string\` o \`json_integer\`

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Para crear la matriz de entrada general para todos sus UTXO, use `json_array`, luego llénelo con objetos usando` json_array_append`:
usando \`json_array_append\`:

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +Para crear la matriz de salida para su transacción, siga el mismo formato, cree un objeto JSON con `json_object`, luego llénelo con` json_object_set`:
con \`json_object_set\`:

2021-08-05 01:45 UTC, icculp commented on es/16_2_Programando_Bitcoind_en_C_con_las_Bibliotecas_RPC.md
> +El código completo se puede encontrar en el [directorio src](src/15_2_sendtoaddress.c).
../src/15_2_sendtoaddress.c

2021-08-05 17:43 UTC, icculp approved these changes

2021-08-05 17:43 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:13 UTC, shannona commented
merging.

2021-08-10 18:13 UTC, merged