Chapter 16-3 16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_Z…
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #352
Opened 2021-07-29 17:32 UTC by javiervargas

…MQ.md

2021-08-05 02:23 UTC, icculp requested changes

2021-08-05 02:23 UTC, icculp commented on es/16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_ZMQ.md
> +Puede ejecutar `bitcoind` con argumentos de línea de comandos para puntos finales ZMQ, como se muestra arriba, pero también puede hacer que un punto final sea accesible agregando líneas apropiadas a
archivo \`~/.bitcoin/bitcoin.conf\` y

2021-08-05 02:23 UTC, icculp commented on es/16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_ZMQ.md
> +''
\`\`\`

2021-08-05 02:23 UTC, icculp commented on es/16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_ZMQ.md
> +''
\`\`\`

2021-08-05 02:23 UTC, icculp commented on es/16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_ZMQ.md
> +El programa requiere dos parámetros: el primer parámetro es el "servidor", que es el punto de conexión TCP expuesto por `bitcoind`; y el segundo es el "tema", que actualmente es `zmqpubhashblock`,` z
o \`zmqpubrawtx\`.

2021-08-05 02:23 UTC, icculp commented on es/16_3_Recibiendo_Notificaciones_de_Bitcoind_en_C_con_las_Bibliotecas_ZMQ.md
> +El código fuente está en el [directorio src](src/15_3_chainlistener.c) como de costumbre. Debería compilarlo:
../src/15_3_chainlistener.c

2021-08-05 17:41 UTC, icculp approved these changes

2021-08-05 17:41 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:14 UTC, shannona commented
Thanks.

2021-08-10 18:14 UTC, merged