Chapter 17-1 17_1_Configurando_Libwally.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #354
Opened 2021-07-29 17:35 UTC by javiervargas

2021-08-03 03:33 UTC, icculp requested changes

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +# 16.1: Configuración de Libwally
17.1

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +El directorio src contiene [testwally. c](src/16_1_testwally.c), que sólo muestra cómo funcionan las funciones de inicialización y limpieza.
testwally.c (remove space), also link doesn't work since it's in a lower directory. try ..src/16_1_testwally.c or full path

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +$ . /herramientas/autogen.sh
./tools/autogen.sh
(code shouldn't be translated)

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +$ . /configure
./configure
(remove space)

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +Entonces, ¿cómo usar Libwally en un programa? Como de costumbre,usted necesitara incluir archivos apropiados y enlazar bibliotecas apropiadas para su código.
costumbre, usted

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +Afortunadamente, los nombres de archivo coinciden en gran medida con las secciones de [docs](https://wally.readthedocs.io/en/latest/), por lo que debería ser capaz de incluir los archivos correctos e
wally_core.h
(remove space)

2021-08-03 03:33 UTC, icculp commented on es/17_1_Configurando_Libwally.md
> +Más información sobre "Programar Bitcoin con Libwally" en [16.2: Usar BIP39 en Libwally](16_2_Using_BIP39_in_Libwally.md).
```
[17.2: Usando BIP39 en Libwally](17_2_Usando_BIP39_en_Libwally.md).
```

2021-08-05 17:31 UTC, icculp approved these changes

2021-08-05 17:31 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:21 UTC, shannona commented
Great, thanks.

2021-08-10 18:21 UTC, merged