Chapter 17-5 17_5_Usando_Scripts_en_Libwally.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #358
Opened 2021-07-29 17:39 UTC by javiervargas

2021-08-04 14:06 UTC, icculp requested changes

2021-08-04 14:06 UTC, icculp commented on es/17_5_Usando_Scripts_en_Libwally.md
> +> :fire: ***Cuál es el poder de los guiones en Libwally?*** Simplemente, puedes hacer algo que no podías hacer antes: crear una transacción bloqueada con un P2SH arbitrario.
que no podía

2021-08-04 14:06 UTC, icculp commented on es/17_5_Usando_Scripts_en_Libwally.md
> +Puede tomar el código de prueba del [directorio src](src/16_5_replacewithscript.c) y compilarlo:
../src/16_5_replacewithscript.c

2021-08-05 17:21 UTC, icculp approved these changes

2021-08-05 17:21 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:22 UTC, shannona commented
thank you

2021-08-10 18:22 UTC, merged