Chapter 17-6 17_6_Usando_Otras_Funciones_en_Libwally.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #359
Opened 2021-07-29 17:40 UTC by javiervargas

2021-08-04 14:44 UTC, icculp requested changes

2021-08-04 14:44 UTC, icculp commented on es/17_6_Usando_Otras_Funciones_en_Libwally.md
> +   * `wally_addr_segwit_to_bytes` - Convertir una dirección Segwit en un scriptPubKey` (en bytes)
\`scriptPubKey\`

2021-08-05 17:20 UTC, icculp approved these changes

2021-08-05 17:20 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:22 UTC, shannona commented
Great

2021-08-10 18:22 UTC, merged