Chapter 18-6 18_6_Accediendo_a_Bitcoind_con_Swift.md
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #367
Opened 2021-07-29 17:48 UTC by javiervargas

2021-08-01 20:05 UTC, icculp requested changes

2021-08-01 20:05 UTC, icculp commented on es/18_6_Accediendo_a_Bitcoind_con_Swift.md
> +Como en otros ejemplos, usted va a tomar arbitrariamente el 0º UTXO, y usara las `txid`, `vout`, y `amount` de ella.
usar o usará?

2021-08-01 20:05 UTC, icculp commented on es/18_6_Accediendo_a_Bitcoind_con_Swift.md
> +La firma de su transacción sólo requiere que ejecute la transacción `signrawctionwithwallet`RPC, usando su nuevo `hex`:
\`signrawctionwithwallet\` RPC,

2021-08-05 17:19 UTC, icculp approved these changes

2021-08-05 17:19 UTC, icculp commented
@shannona ready to be merged

2021-08-10 18:23 UTC, shannona commented
Terrific.

2021-08-10 18:23 UTC, merged