Create 04_0_Enviando_Transacciones_Bitcoin
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #409
Opened 2021-08-10 17:30 UTC by srahalh

2021-08-16 13:51 UTC, javiervargas reviewed
pending fix links

2021-08-20 15:35 UTC, icculp commented
Need to rename the file to 04_0_Enviando_Transacciones_Bitcoin.md, appending ".md" to the filename, otherwise github won't recognize it as markdown and the formatting doesn't show.

2021-08-20 15:43 UTC, javiervargas commented
x

> Need to rename the file to 04_0_Enviando_Transacciones_Bitcoin.md, appending ".md" to the filename, otherwise github won't recognize it as markdown and the formatting doesn't show.

Sure,  I think it happens on all four chapters.

2021-08-20 15:50 UTC, icculp requested changes

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Uno: Enviando Monedas de Forma Sencilla](04_1_Sending_Coins_The_Easy_Way.md)
`* [Sección Uno: Enviando Monedas de la Forma Fácil](04_0_Enviando_Transacciones_Bitcoin.md)`
to match the titles and links in LEEME.md

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Dos: Creando una Transacción en Crudo](04_2_Creating_a_Raw_Transaction.md)
`[4.2: Creando una Transacción Cruda](04_2_Creando_una_Transaccion_Cruda.md)`

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +     * [Interludio: Usando JQ](04_2__Interlude_Using_JQ.md)
`[Interludio: Usando JQ](04_2__Interludio_Usando_JQ.md)`

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Tres: Creando Transacciones en Crudo Usando Argumentos con Nombre](04_3_Creating_a_Raw_Transaction_with_Named_Arguments.md)
`[4.3: Creando una Transacción Cruda con Argumentos Ingresados con Nombre](04_3_Creando_una_Transaccion_Cruda_con_Argumentos_Ingresados_con_Nombre.md)`

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Cuatro: Enviando Monedas con Transacciones en Crudo](04_4_Sending_Coins_with_a_Raw_Transaction.md)
`[4.4: Enviando Monedas con una Transacción Cruda](04_4_Enviando_Monedas_con_una_Transaccion_Cruda.md)`

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Cuatro: Enviando Monedas con Transacciones en Crudo](04_4_Sending_Coins_with_a_Raw_Transaction.md)
`     * [Interludio: Usando Curl](04_4__Interludio_Usando_Curl.md)`
add interlude, PR #427

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Cinco: Enviando Monedas con Transacciones Automatizadas en Crudo](04_5_Sending_Coins_with_Automated_Raw_Transactions.md)
`[4.5: Enviando Monedas con Transacciones Crudas Automatizadas](04_5_Enviando_Monedas_con_Transacciones_Crudas_Automatizadas.md)`

2021-08-20 15:50 UTC, icculp commented on es/04_0_Enviando_Transacciones_Bitcoin
> +  * [Sección Seis: Creando Transacciones SegWit](04_6_Creating_a_Segwit_Transaction.md)
`[4.6: Creando una Transacción Segwit](04_6_Creando_una_Transaccion_Segwit.md)`

2021-08-23 16:27 UTC, icculp approved these changes

2021-08-23 16:28 UTC, icculp commented
I think it looks good, @shannona ready to be merged

2021-08-31 19:01 UTC, merged