04_2_Interludio_Usando_JQ
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #412
Opened 2021-08-10 17:35 UTC by srahalh

2021-08-21 22:53 UTC, icculp commented
rename to 04_2__Interludio_Usando_JQ.md
(note the extra _ so the link works)

2021-08-21 23:36 UTC, icculp requested changes

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Sacar datos de un objeto JSON es fácil, pero ¿Qué pasa si ese objeto JSON está en un arreglo JSON? El comando `listunspent` ofrece un gran ejemplo, porque normalmente contendrá un número de transacci
Y si quiere capturar

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Cuando se trabaja con un array JSON, lo primero que hay que hacer es decirle a JQ a qué índice debe acceder. Por ejemplo, puede que hayas mirado tus transacciones en `listunspent` y hayas decidido qu
que haya mirado sus transacciones

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Cuando se trabaja con un array JSON, lo primero que hay que hacer es decirle a JQ a qué índice debe acceder. Por ejemplo, puede que hayas mirado tus transacciones en `listunspent` y hayas decidido qu
y haya decidido que quiere trabajar

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Afortunadamente, JQ también te permite ser elegante. Puedes usar `{}`s para crear nuevos objetos JSON (ya sea para un análisis adicional o para una salida bonita). También puede definir el nombre de
Puede usar

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +You could of course rename your new keys as you see fit. There's nothing magic in the original names:
Por supuesto, puede cambiar el nombre de sus nuevas llaves como mejor se parezca. No hay nada mágico en los nombres originales.

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Hasta ahora, las búsquedas en JQ han sido bastante sencillas: se utiliza una clave para buscar uno o más valores en un objeto o arreglo JSON. ¿Pero qué pasa si quieres buscar un valor en un objeto JS
si quiere buscar

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Hasta ahora, las búsquedas en JQ han sido bastante sencillas: se utiliza una clave para buscar uno o más valores en un objeto o arreglo JSON. ¿Pero qué pasa si quieres buscar un valor en un objeto JS
puede permitir calcular

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +### Recuperar el(los) valor(es)
`### Recuperar los valores`

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +> :advertencia: **ADVERTENCIA:** Recuerde siempre que un UTXO es una transacción _más_ un vout. La primera vez que escribimos este ejemplo de JQ se nos escapó el vout, y dejó de funcionar cuando acab
`> :warning: **ADVERTENCIA:**`

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Ahora puedes ir un paso más allá, y solicitar el .amount (o cualquier otro valor-clave JSON) de los UTXOs que estás recuperando.
puede ir

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Ahora puedes ir un paso más allá, y solicitar el .amount (o cualquier otro valor-clave JSON) de los UTXOs que estás recuperando.
está recuperando

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Para completar el cálculo de la tasa de transacción, se resta el importe de .vout (1,045) del importe de .vin (1,3).
(1.045)
(1.3)

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +> :advertencia: **ADVERTENCIA:** La primera vez que escribimos esta lección, realmente calculamos mal nuestra tarifa y no lo vimos hasta que ejecutamos nuestra calculadora de tarifas. Es *así de fáci
`> :warning: **ADVERTENCIA:**`

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +El código JQ puede ser un poco difícil de manejar, así que deberías considerar añadir algunas invocaciones más largas e interesantes a tu ~/.bash_profile.
que debería

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +El código JQ puede ser un poco difícil de manejar, así que deberías considerar añadir algunas invocaciones más largas e interesantes a tu ~/.bash_profile.
interesantes a su

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Cada vez que busques una gran cantidad de información en un objeto JSON emitido por un comando `bitcoin-cli`, considera escribir un alias para reducirlo a lo que quieres ver.
que busque

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Cada vez que busques una gran cantidad de información en un objeto JSON emitido por un comando `bitcoin-cli`, considera escribir un alias para reducirlo a lo que quieres ver.
lo que quiere ver

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +El [Fee Calculation Script](src/04_2_i_txfee-calc.sh) está disponible en el directorio src-code. Puede descargarlo y guardarlo como `txfee-calc.sh`.
`[Guión de cálculo de tasas](../src/04_2_i_txfee-calc.sh)`

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +> :advertencia: **ADVERTENCIA:** Este script no ha sido verificado de forma robusta. Si va a utilizarlo para verificar las comisiones de las transacciones reales, sólo deberá hacerlo como triple comp
`> :warning: **ADVERTENCIA:**`

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +También puedes crear un alias:
puede

2021-08-21 23:36 UTC, icculp commented on es/04_2_Interludio_Usando_JQ
> +Continua "Enviando Transacciones en Bitcoin" con [§4.3 Creando Transacciones en Crudo Usando Argumentos con Nombre](04_3_Creating_a_Raw_Transaction_with_Named_Arguments.md).
(04_3_Creando_una_Transaccion_Cruda_con_Argumentos_Ingresados_con_Nombre.md)

2021-08-29 23:28 UTC, icculp requested changes
A few changes remaining. Also, please note the extra _ in the filename and rename it thus as the other links are interlude links all have two __ in them

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +Hasta ahora, las búsquedas en JQ han sido bastante sencillas: se utiliza una clave para buscar uno o más valores en un objeto o arreglo JSON. ¿Pero qué pasa si quieres buscar un valor en un objeto JS
si quiere buscar

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +Hasta ahora, las búsquedas en JQ han sido bastante sencillas: se utiliza una clave para buscar uno o más valores en un objeto o arreglo JSON. ¿Pero qué pasa si quieres buscar un valor en un objeto JS
puede permitirse calcular

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +Ahora puedes ir un paso más allá, y solicitar el .amount (o cualquier otro valor-clave JSON) de los UTXOs que estás recuperando.
Ahora puede ir

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +Ahora puedes ir un paso más allá, y solicitar el .amount (o cualquier otro valor-clave JSON) de los UTXOs que estás recuperando.
que está recuperando.

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +Para completar el cálculo de la tasa de transacción, se resta el importe de .vout (1,045) del importe de .vin (1,3).
(1.045)
(1.3)

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +El código JQ puede ser un poco difícil de manejar, así que debería considerar añadir algunas invocaciones más largas e interesantes a tu ~/.bash_profile.
e interesantes a su

2021-08-29 23:28 UTC, icculp commented on es/04_2_Interludio_Usando_JQ.md
> +El [Fee Calculation Script](src/04_2_i_txfee-calc.sh) está disponible en el directorio src-code. Puede descargarlo y guardarlo como `txfee-calc.sh`.
[Guión de cálculo de tasas](../src/04_2_i_txfee-calc.sh)

2021-09-14 20:47 UTC, icculp commented
> rename to 04_2__Interludio_Usando_JQ.md
> (note the extra _ so the link works)

Link with double underscore fixed in readme to have only 1, so filename is fine as it is now. (04_2_Interludio_Usando_JQ.md)

2021-09-26 19:04 UTC, icculp approved these changes
@shannona ready to be merged

2021-09-28 18:27 UTC, shannona commented
Yay!

2021-09-28 18:27 UTC, merged