04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_c…
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #413
Opened 2021-08-10 17:37 UTC by srahalh

…on_Nombre

2021-08-18 20:02 UTC, javiervargas reviewed
Please update links

2021-08-22 19:05 UTC, icculp commented
rename file to 04_3_Creando_una_Transaccion_Cruda_con_Argumentos_Ingresados_con_Nombre.md

2021-08-22 19:11 UTC, icculp requested changes

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +> : advertencia: **ADVERTENCIA DE VERSIÓN:** Esta es una innovación de Bitcoin Core v 0.14.0. Si ha utilizado nuestros scripts de instalación, es lo que debería tener, pero vuelva a comprobar su vers
`> : warning: **ADVERTENCIA DE VERSIÓN:**`

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +Para utilizar un argumento con nombre debe ejecutar `bitcoin-cli` con el argumento `-named`. Si planeas hacer esto regularmente, probablemente querrás crear un alias:
Si planea

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +Para utilizar un argumento con nombre debe ejecutar `bitcoin-cli` con el argumento `-named`. Si planeas hacer esto regularmente, probablemente querrás crear un alias:
probablemente querrá

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +> : advertencia: **ADVERTENCIA DE VERSIÓN:** Aquí es donde aparece el error en Bitcoin Core 0.14: el argumento 'inputs' para 'createrawtransaction' se llama erróneamente 'transactions'. Así que, si e
`> : warning: **ADVERTENCIA DE VERSIÓN:**`

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +Ejecutando `bitcoin-cli` con la bandera `-named`, puedes utilizar argumentos con nombre en lugar de depender de argumentos ordenados. La ayuda de `bitcoin-cli` le mostrará siempre el nombre correcto
puede utilizar

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +Esta documentación utilizará argumentos con nombre para todos los ejemplos futuros, por claridad y para establecer las mejores prácticas. Sin embargo, también mostrará todos los argumentos en el orde
Missing first _ in this paragraph for italics

2021-08-22 19:11 UTC, icculp commented on es/04_3_Creando_una_Transacción_Cruda_con_Argumentos_Ingresados_con_Nombre
> +Continuar "Enviando transacciones de Bitcoin" con [§4.4: Sending Coins with Raw Transactions](04_4_Sending_Coins_with_a_Raw_Transaction.md).
[§4.4: Enviando Monedas con una Transacción Cruda](04_4_Enviando_Monedas_con_una_Transaccion_Cruda.md)

2021-08-29 23:30 UTC, icculp approved these changes
@shannona ready to be merged

2021-08-31 19:04 UTC, merged