chapter 7.3 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #448
Opened 2021-09-04 18:37 UTC by icculp

2021-09-04 19:52 UTC, javiervargas requested changes

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +HWI es un programa de Bitcoin Core disponible en Python que se puede utilizar para interactuar con carteras de hardware.
billeteras de hardware.

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Si no tiene `git` ya instalado en su Mac, puede hacerlo simplemente intentando ejecutarlo: `git --version`.
Si aun no tiene `git` instalado en su Mac, puede hacerlo simplemente intentando ejecutarlo así:

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +También querrá crear un alias aquí, variado según su ubicación de instalación real:
variará según la ubicación real de su instalación:

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +2. Vaya al "Administrador" e instale "Prueba de Bitcoin". La versión actual requiere que primero instales "Bitcoin" y "Ethereum".
La versión actual requiere que primero instale "Bitcoin" y "Ethereum".

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Para que un libro mayor sea accesible, debe iniciar sesión con su PIN y luego abrir la aplicación que desea usar, en este caso, la aplicación "Prueba de Bitcoin". Es posible que deba repetir esto de
si su Ledger entra en reposo.

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Para usar su billetera de hardware con `bitcoin-cli`, querrá crear una billetera con nombre específico en Bitcoin Core, usando el RPC `createwallet`, que es un comando que no hemos discutido anterior
usando el comando RPC `createwallet`,

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +En este caso, está creando un nuevo `ledger` de billetera sin claves privadas (ya que estas terminarán en el dispositivo de Ledger).
de billetera sin claves privadas (ya que éstas terminarán en el dispositivo de Ledger).

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +> :book: ***¿Por qué nombrar carteras?*** Hasta la fecha, este curso ha utilizado la billetera predeterminada ("") en Bitcoin Core. Esto está bien para muchos propósitos, pero es inadecuado si tiene
***¿Por qué nombrar billeteras?***

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Nos dirigimos a HWI con la `huella digital` y pedimos las primeras 1000 direcciones WPKH (Segwit nativo). A cambio, recibimos dos descriptores para el grupo de claves: uno para recibir direcciones y
uno para las direcciones de recepción y otro para las direcciones de cambio.

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Obviamente, recibir una transacción es sencillo. Utiliza `getnewaddress` para solicitar una de esas direcciones importadas:
Utilice `getnewaddress` para solicitar una de esas direcciones importadas:

2021-09-04 19:52 UTC, javiervargas commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Luego envíaselo dinero.
Luego envíele dinero.

2021-09-04 23:05 UTC, icculp commented on es/07_3_Integrando_con_Hardware_Wallets.md
> +Tiene tres opciones para avanzar a través de este capítulo sobre carteras de hardware: (1) leer sin probar el código; (2) instale Bitcoin en una máquina local para probar completamente estos comandos
Will search and replace all instances

2021-09-05 09:38 UTC, javiervargas approved these changes
@shannona ready to merge

2021-09-07 18:02 UTC, shannona commented
Thanks.

2021-09-07 18:02 UTC, merged