6.0
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #462
Opened 2021-09-08 19:20 UTC by maxcrowar

2021-09-09 14:19 UTC, icculp requested changes

2021-09-09 14:19 UTC, icculp commented on es/06_0_Expandiendo_las_Transacciones_Bitcoin_con_Multifirmas.md
> +Transacciones Básicas bitcoin: (1) enviar fondos; (2) a un destinatario P2PKH simple o SegWit; (3) desde una máquina; (4) inmediatamente. Sin embargo, estas cuatro partes de esta definición pueden ex
Transacciones básicas Bitcoin

2021-09-09 21:14 UTC, icculp approved these changes
@shannona ready to be merged

2021-09-14 18:33 UTC, shannona commented
Great! Thanks @maxcrowar!

2021-09-14 18:33 UTC, merged