6.3
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #465
Opened 2021-09-08 19:43 UTC by maxcrowar

2021-09-09 14:29 UTC, icculp requested changes

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> + # 6.3: Enviando & Gastando una Multisig Automatizada
space in front of first #

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +La técnica estándar para crear direcciones de multifirma y para gastar sus fondos es compleja, pero es un ejercicio que vale la pena para comprender un poco más sobre cómo funcionan y cómo puedes man
puede manipularlas
las multifirmas

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +## Crear una Dirección Multisig en Tu Billetera
Dirección Multifirma en Su

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Para que los fondos enviados a direcciones multisig sean más fáciles de gastar, solo necesita hacer algunos preparativos usando el comando `addmultisigaddress`. Probablemente no sea lo que te gustarí
direcciones multifirma
que se gustaría
si estuviera
solo estuviera
podría ahorrarle

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +A continuación, creas la multisig en _cada máquina que aporta firmas_ usando un nuevo comando, `addmultisigaddress`, en lugar de `createmultisig`. Este nuevo comando guarda parte de la información en
crea la multifirma

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Como se señaló en la sección anterior, actualmente no importa si usas direcciones o claves públicas, por lo que mostramos el otro mecanismo aquí, mezclando los dos. Obtendrás la misma dirección multi
si usa direcciones
Obtendrá la misma

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Posteriormente, los miembros de la multisig aún necesitarán ejecutar `importaddress` para estar atentos a los fondos recibidos en la dirección multisig:
de la multifirma
en la dirección multifirma:

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Posteriormente, podrás recibir fondos en la dirección multifirma como de costumbre. El uso de `addmultisigaddress` es simplemente una cuestión burocrática por parte de los destinatarios: un poco de c
podrá recibir

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Comienzas recolectando tus variables, pero ya no tienes que preocuparte por `scriptPubKey` o `redeemScript`.
sus variables
ya no tiene que

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Aquí hay una nueva transacción enviada a nuestra nueva dirección multisig:
dirección multifirma

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Luego la firmas:
la firma:

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Ten en cuenta que ya no tienes que darle ayuda extra a `signrawtransactionwithkey`, porque toda esa información adicional ya estaba en tu billetera. Lo más importante es que no haz hecho vulnerables
sus claves privadas

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Cuando todos los que sean necesarios hayan firmado, te irás a las carreras:
se irá a

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Al igual que con el shortcut discutido en [§4.5: Enviando Monedas con Transacciones Crudas Automatizadas](04_5_Enviando_Monedas_con_Transacciones_Crudas_Automatizadas.md), el resultado es mucho más s
pero pierde

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Existe una manera más fácil de volver a gastar los fondos enviados a direcciones multisig que simplemente requiere el uso del comando `addmultisigaddress` cuando creas tu dirección. No demuestra las
direcciones multifirma
cuando crea su direcció
no se brinda
solo desea obtener su dinero

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Aprende más acerca de "Expandiendo Transacciones Bitcoin" con [Capítulo Siete: Expandiendo las Transacciones Bitcoin con PSBTs (07_0_Expandiendo_las_Transacciones_Bitcoin_con_PSBTs.md).
con PSBTs](07_0_

2021-09-09 14:29 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Aprende más acerca de "Expandiendo Transacciones Bitcoin" con [Capítulo Siete: Expandiendo las Transacciones Bitcoin con PSBTs (07_0_Expandiendo_las_Transacciones_Bitcoin_con_PSBTs.md).
closing bracket

2021-09-09 22:20 UTC, icculp requested changes

2021-09-09 22:20 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +# 6.3: Enviando & Gastando una Multisig Automatizada
Multifirma

2021-09-09 22:20 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +## Crear una Dirección Multisig en Su Billetera
Multifirma

2021-09-09 22:20 UTC, icculp commented on es/06_3_Enviando_una_Multifirma_Automatizada.md
> +Empieza creando direcciones P2PKH y recuperando claves públicas, como es habitual, para cada usuario que formará parte de la multisig:
de la multifirma:

2021-09-09 22:27 UTC, icculp approved these changes
@shannona ready to be merged

2021-09-14 18:34 UTC, shannona commented
Terrific! Thanks for chapter 6, folks.

2021-09-14 18:34 UTC, merged