Chapter 3.0 translated, pending review
BlockchainCommons/Learning-Bitcoin-from-the-Command-Line pull request #469
Opened 2021-09-14 20:34 UTC by icculp

2021-09-15 00:10 UTC, csralvall requested changes

2021-09-15 00:10 UTC, csralvall commented on es/03_0_Entendiendo_Su_Configuracion_Bitcoin.md
> +Para este y futuros capítulos, suponemos que tienes un VPS con Bitcoin instalado, ejecutando `bitcoind`. También suponemos que está conectado a testnet, lo que le permite acceder a bitcoins sin utili
`...suponemos que tiene un VPS con...`

2021-09-15 00:10 UTC, csralvall commented on es/03_0_Entendiendo_Su_Configuracion_Bitcoin.md
> +   * Demuestre que su nodo Bitcoin está instalado y actualizado
- `* Demostrar que su nodo Bitcoin...`

2021-09-15 00:10 UTC, csralvall commented on es/03_0_Entendiendo_Su_Configuracion_Bitcoin.md
> +   * Cree una dirección para recibir fondos de Bitcoin
- `* Crear una dirección para ...`

2021-09-15 00:10 UTC, csralvall commented on es/03_0_Entendiendo_Su_Configuracion_Bitcoin.md
> +* [Sección Three: Configurando Su Billetera](03_3_Configurando_Su_Billetera.md)
- `* [Sección Tres:...`

2021-09-15 00:10 UTC, csralvall commented on es/03_0_Entendiendo_Su_Configuracion_Bitcoin.md
> +* [Sección Recibiendo una Transacción](03_4_Recibiendo_una_Transaccion.md)
- `* [Sección cuatro`

2021-09-28 11:45 UTC, csralvall approved these changes
@shannona, ready for merge.

2021-09-28 18:29 UTC, shannona commented
Great.

2021-09-28 18:29 UTC, merged